export const FONT_REGISTRY = [
  { label: "Inter", value: "'Inter', sans-serif" },
  { label: "Roboto", value: "'Roboto', sans-serif" },
  { label: "Poppins", value: "'Poppins', sans-serif" },
  { label: "Lato", value: "'Lato', sans-serif" },
  { label: "Montserrat", value: "'Montserrat', sans-serif" },
  { label: "Abel", value: "'Abel', sans-serif" },
  { label: "Open Sans", value: "'Open Sans', sans-serif" },
  { label: "Oswald", value: "'Oswald', sans-serif" },
  { label: "Noto Sans", value: "'Noto Sans', sans-serif" },
  { label: "Raleway", value: "'Raleway', sans-serif" },
  { label: "Rubik", value: "'Rubik', sans-serif" },
  { label: "Playfair Display", value: "'Playfair Display', serif" },
  { label: "Ubuntu", value: "'Ubuntu', sans-serif" },
  { label: "Merriweather", value: "'Merriweather', serif" },
  { label: "Anuphan", value: "'Anuphan', sans-serif" },
  { label: "PT Sans", value: "'PT Sans', sans-serif" },
  { label: "Source Sans 3", value: "'Source Sans 3', sans-serif" },
  { label: "Lora", value: "'Lora', serif" },
  { label: "Manrope", value: "'Manrope', sans-serif" },
  { label: "Titillium Web", value: "'Titillium Web', sans-serif" },
  { label: "Kode Mono", value: "'Kode Mono', monospace" },
  { label: "Nunito", value: "'Nunito', sans-serif" },
  { label: "Bricolage Grotesque", value: "'Bricolage Grotesque', sans-serif" },
  { label: "Syne", value: "'Syne', sans-serif" },
  { label: "Michroma", value: "'Michroma', sans-serif" },
  { label: "Dancing Script", value: "'Dancing Script', cursive" },
  { label: "Share Tech", value: "'Share Tech', sans-serif" },
  { label: "Work Sans", value: "'Work Sans', sans-serif" },
  { label: "Sansation", value: "'Sansation', sans-serif" },
  { label: "Pacifico", value: "'Pacifico', cursive" },
  { label: "Comic Relief", value: "'Comic Relief', cursive" },
  { label: "Prompt", value: "'Prompt', sans-serif" },
  { label: "Alegreya", value: "'Alegreya', serif" },
  { label: "Comfortaa", value: "'Comfortaa', sans-serif" },
];
