import {
    IconSettings,
    IconCloud,
    IconShield,
    IconUsers,
    IconChartBar,
    IconMessageCircle,
    IconBell,
    IconHome,
    IconDatabase,
    IconFileText,
    IconLock,
    IconCalendar,
    IconCreditCard,
    IconMapPin,
    IconPlug,
    IconCode,
    IconDeviceLaptop,
    IconMicrophone,
    IconCamera,
    IconRobot,
    IconBuildingSkyscraper,
    IconMail,
    IconSearch,
    IconHelp,
} from "@tabler/icons-react";

import {
    Server,
    Globe,
    LifeBuoy,
    Rocket,
    Building2,
    Wallet,
    ShoppingCart,
    Clock,
    Eye,
    Lightbulb,
    Zap,
    Layers,
    UploadCloud,
    Archive,
} from "lucide-react";

type IconOption = {
    label: string;
    icon: React.ReactNode;
};

export const ICONS_REGISTRY: IconOption[] = [
    { label: "Cloud", icon: <IconCloud size={20} /> },
    { label: "Security", icon: <IconShield size={20} /> },
    { label: "Analytics", icon: <IconChartBar size={20} /> },
    { label: "Support", icon: <LifeBuoy className="w-5 h-5" /> },
    { label: "Settings", icon: <IconSettings size={20} /> },
    { label: "Users", icon: <IconUsers size={20} /> },
    { label: "Server", icon: <Server className="w-5 h-5" /> },
    { label: "Global", icon: <Globe className="w-5 h-5" /> },
    { label: "Chat", icon: <IconMessageCircle size={20} /> },
    { label: "Notifications", icon: <IconBell size={20} /> },
    { label: "Launch", icon: <Rocket className="w-5 h-5" /> },
    { label: "Enterprise", icon: <IconBuildingSkyscraper size={20} /> },
    { label: "Documents", icon: <IconFileText size={20} /> },
    { label: "Database", icon: <IconDatabase size={20} /> },
    { label: "Payments", icon: <IconCreditCard size={20} /> },
    { label: "Wallet", icon: <Wallet className="w-5 h-5" /> },
    { label: "E-Commerce", icon: <ShoppingCart className="w-5 h-5" /> },
    { label: "Map", icon: <IconMapPin size={20} /> },
    { label: "Calendar", icon: <IconCalendar size={20} /> },
    { label: "Integration", icon: <IconPlug size={20} /> },
    { label: "Code", icon: <IconCode size={20} /> },
    { label: "Devices", icon: <IconDeviceLaptop size={20} /> },
    { label: "Microphone", icon: <IconMicrophone size={20} /> },
    { label: "Camera", icon: <IconCamera size={20} /> },
    { label: "AI", icon: <IconRobot size={20} /> },
    { label: "Email", icon: <IconMail size={20} /> },
    { label: "Home", icon: <IconHome size={20} /> },
    { label: "Search", icon: <IconSearch size={20} /> },
    { label: "Help", icon: <IconHelp size={20} /> },
    { label: "Privacy", icon: <IconLock size={20} /> },
    { label: "Time", icon: <Clock className="w-5 h-5" /> },
    { label: "Vision", icon: <Eye className="w-5 h-5" /> },
    { label: "Ideas", icon: <Lightbulb className="w-5 h-5" /> },
    { label: "Automation", icon: <Zap className="w-5 h-5" /> },
    { label: "Layers", icon: <Layers className="w-5 h-5" /> },
    { label: "Upload", icon: <UploadCloud className="w-5 h-5" /> },
    { label: "Archive", icon: <Archive className="w-5 h-5" /> },
    { label: "Organization", icon: <Building2 className="w-5 h-5" /> },
];
