import {
    IconSettings,
    IconCloud,
    IconShield,
    IconUsers,
    IconChartBar,
    IconMessageCircle,
    IconBell,
    IconHome,
    IconDatabase,
    IconFileText,
    IconLock,
    IconCalendar,
    IconCreditCard,
    IconMapPin,
    IconPlug,
    IconCode,
    IconDeviceLaptop,
    IconMicrophone,
    IconCamera,
    IconRobot,
    IconBuildingSkyscraper,
    IconMail,
    IconSearch,
    IconHelp,
    IconBrandYoutube,
    IconBrandX,
    IconBrandFacebook,
    IconBrandGithub,
    IconBrandInstagram,
    IconBrandLinkedin,
    IconBrandDribbble,
    IconArrowUpRight,
} from "@tabler/icons-react";

import {
    Server,
    Globe,
    LifeBuoy,
    Rocket,
    Building2,
    Wallet,
    ShoppingCart,
    Clock,
    Eye,
    Lightbulb,
    Zap,
    Layers,
    UploadCloud,
    Archive,
    TrendingUp,
    Activity,
    Accessibility,
    AlarmClockCheck,
    AlignHorizontalSpaceAround,
    Anchor,
    Aperture,
    ArrowDown,
    Award,
    Banknote,
    BadgeCheck,
    Bomb,
    Briefcase,
    CalendarCheck,
    CameraOff,
    CheckCheck,
    Check,
    ClipboardCheck,
    CloudDownload,
    CloudOff,
    Cog,
    Copy,
    Cpu,
    Crosshair,
    Crown,
    DatabaseBackup,
    Diamond,
    ExternalLink,
    FileCheck,
    Film,
    Fingerprint,
    Folder,
    Gavel,
    GitBranch,
    Handshake,
    Heart,
    Image,
    Info,
    Kanban,
    Key,
    Laptop,
    LayoutDashboard,
    Link,
    Locate,
    MessageSquare,
    Minus,
    Monitor,
    MousePointer,
    Network,
    Package,
    Palette,
    PenTool,
    Pencil,
    Plus,
    Power,
    Printer,
    Puzzle,
    RefreshCcw,
    RotateCcw,
    Rss,
    Save,
    Scaling,
    ScanText,
    Settings2,
    Share,
    ShieldCheck,
    Signal,
    Skull,
    SlidersHorizontal,
    Sparkles,
    Sun,
    Tent,
    Terminal,
    ThumbsDown,
    ThumbsUp,
    Ticket,
    Timer,
    Trash,
    TrendingDown,
    Truck,
    UserCheck,
    UserX,
    Vote,
    Wand,
    Warehouse,
    Watch,
    Wrench,
    X,
} from "lucide-react";

type IconOption = {
    label: string;
    //eslint-disable-next-line
    icon: (props?: React.ComponentProps<any>) => React.ReactNode;
};

export const ICONS_REGISTRY: IconOption[] = [
    { label: "Cloud", icon: (props) => <IconCloud size={20} {...props} /> },
    { label: "Security", icon: (props) => <IconShield size={20} {...props} /> },
    { label: "ArrowUpRight", icon: (props) => <IconArrowUpRight size={20} {...props} /> },
    { label: "TrendingUp", icon: (props) => <TrendingUp size={20} {...props} /> },
    {
        label: "Analytics",
        icon: (props) => <IconChartBar size={20} {...props} />,
    },
    {
        label: "Support",
        icon: (props) => <LifeBuoy className="w-5 h-5" {...props} />,
    },
    { label: "Settings", icon: (props) => <IconSettings size={20} {...props} /> },
    { label: "Users", icon: (props) => <IconUsers size={20} {...props} /> },
    {
        label: "Server",
        icon: (props) => <Server className="w-5 h-5" {...props} />,
    },
    {
        label: "Global",
        icon: (props) => <Globe className="w-5 h-5" {...props} />,
    },
    {
        label: "Chat",
        icon: (props) => <IconMessageCircle size={20} {...props} />,
    },
    {
        label: "Notifications",
        icon: (props) => <IconBell size={20} {...props} />,
    },
    {
        label: "Launch",
        icon: (props) => <Rocket className="w-5 h-5" {...props} />,
    },
    {
        label: "Enterprise",
        icon: (props) => <IconBuildingSkyscraper size={20} {...props} />,
    },
    {
        label: "Documents",
        icon: (props) => <IconFileText size={20} {...props} />,
    },
    { label: "Database", icon: (props) => <IconDatabase size={20} {...props} /> },
    {
        label: "Payments",
        icon: (props) => <IconCreditCard size={20} {...props} />,
    },
    {
        label: "Wallet",
        icon: (props) => <Wallet className="w-5 h-5" {...props} />,
    },
    {
        label: "E-Commerce",
        icon: (props) => <ShoppingCart className="w-5 h-5" {...props} />,
    },
    { label: "Map", icon: (props) => <IconMapPin size={20} {...props} /> },
    { label: "Calendar", icon: (props) => <IconCalendar size={20} {...props} /> },
    { label: "Integration", icon: (props) => <IconPlug size={20} {...props} /> },
    { label: "Code", icon: (props) => <IconCode size={20} {...props} /> },
    {
        label: "Devices",
        icon: (props) => <IconDeviceLaptop size={20} {...props} />,
    },
    {
        label: "Microphone",
        icon: (props) => <IconMicrophone size={20} {...props} />,
    },
    { label: "Camera", icon: (props) => <IconCamera size={20} {...props} /> },
    { label: "AI", icon: (props) => <IconRobot size={20} {...props} /> },
    { label: "Email", icon: (props) => <IconMail size={20} {...props} /> },
    { label: "Home", icon: (props) => <IconHome size={20} {...props} /> },
    { label: "Search", icon: (props) => <IconSearch size={20} {...props} /> },
    { label: "Help", icon: (props) => <IconHelp size={20} {...props} /> },
    { label: "Privacy", icon: (props) => <IconLock size={20} {...props} /> },
    { label: "Time", icon: (props) => <Clock className="w-5 h-5" {...props} /> },
    { label: "Vision", icon: (props) => <Eye className="w-5 h-5" {...props} /> },
    {
        label: "Ideas",
        icon: (props) => <Lightbulb className="w-5 h-5" {...props} />,
    },
    {
        label: "Automation",
        icon: (props) => <Zap className="w-5 h-5" {...props} />,
    },
    {
        label: "Layers",
        icon: (props) => <Layers className="w-5 h-5" {...props} />,
    },
    {
        label: "Upload",
        icon: (props) => <UploadCloud className="w-5 h-5" {...props} />,
    },
    {
        label: "Archive",
        icon: (props) => <Archive className="w-5 h-5" {...props} />,
    },
    {
        label: "Organization",
        icon: (props) => <Building2 className="w-5 h-5" {...props} />,
    },
    { label: "Arrow Down", icon: (props) => <ArrowDown className="w-5 h-5" {...props} /> },
    { label: "Check", icon: (props) => <Check className="w-5 h-5" {...props} /> },
    { label: "Cross", icon: (props) => <X className="w-5 h-5" {...props} /> },
    { label: "Plus", icon: (props) => <Plus className="w-5 h-5" {...props} /> },
    { label: "Minus", icon: (props) => <Minus className="w-5 h-5" {...props} /> },
    { label: "Lock", icon: (props) => <IconLock className="w-5 h-5" {...props} /> },
    { label: "Link", icon: (props) => <Link className="w-5 h-5" {...props} /> },
    { label: "Activity", icon: (props) => <Activity className="w-5 h-5" {...props} /> },
    { label: "Accessibility", icon: (props) => <Accessibility className="w-5 h-5" {...props} /> },
    { label: "Alarm Clock", icon: (props) => <AlarmClockCheck className="w-5 h-5" {...props} /> },
    { label: "Settings 2", icon: (props) => <Settings2 className="w-5 h-5" {...props} /> },
    { label: "Share", icon: (props) => <Share className="w-5 h-5" {...props} /> },
    { label: "Shield Check", icon: (props) => <ShieldCheck className="w-5 h-5" {...props} /> },
    { label: "Sliders", icon: (props) => <SlidersHorizontal className="w-5 h-5" {...props} /> },
    { label: "Sparkles", icon: (props) => <Sparkles className="w-5 h-5" {...props} /> },
    { label: "Terminal", icon: (props) => <Terminal className="w-5 h-5" {...props} /> },
    { label: "Thumbs Up", icon: (props) => <ThumbsUp className="w-5 h-5" {...props} /> },
    { label: "Thumbs Down", icon: (props) => <ThumbsDown className="w-5 h-5" {...props} /> },
    { label: "Trash", icon: (props) => <Trash className="w-5 h-5" {...props} /> },
    { label: "User Check", icon: (props) => <UserCheck className="w-5 h-5" {...props} /> },
    { label: "Wrench", icon: (props) => <Wrench className="w-5 h-5" {...props} /> },
    { label: "Align Horizontal Space Around", icon: (props) => <AlignHorizontalSpaceAround className="w-5 h-5" {...props} /> },
    { label: "Anchor", icon: (props) => <Anchor className="w-5 h-5" {...props} /> },
    { label: "Aperture", icon: (props) => <Aperture className="w-5 h-5" {...props} /> },
    { label: "Award", icon: (props) => <Award className="w-5 h-5" {...props} /> },
    { label: "Banknote", icon: (props) => <Banknote className="w-5 h-5" {...props} /> },
    { label: "Badge Check", icon: (props) => <BadgeCheck className="w-5 h-5" {...props} /> },
    { label: "Bomb", icon: (props) => <Bomb className="w-5 h-5" {...props} /> },
    { label: "Briefcase", icon: (props) => <Briefcase className="w-5 h-5" {...props} /> },
    { label: "Calendar Check", icon: (props) => <CalendarCheck className="w-5 h-5" {...props} /> },
    { label: "Camera Off", icon: (props) => <CameraOff className="w-5 h-5" {...props} /> },
    { label: "Check Check", icon: (props) => <CheckCheck className="w-5 h-5" {...props} /> },
    { label: "Clipboard Check", icon: (props) => <ClipboardCheck className="w-5 h-5" {...props} /> },
    { label: "Cloud Download", icon: (props) => <CloudDownload className="w-5 h-5" {...props} /> },
    { label: "Cloud Off", icon: (props) => <CloudOff className="w-5 h-5" {...props} /> },
    { label: "Cog", icon: (props) => <Cog className="w-5 h-5" {...props} /> },
    { label: "Copy", icon: (props) => <Copy className="w-5 h-5" {...props} /> },
    { label: "CPU", icon: (props) => <Cpu className="w-5 h-5" {...props} /> },
    { label: "Crosshair", icon: (props) => <Crosshair className="w-5 h-5" {...props} /> },
    { label: "Crown", icon: (props) => <Crown className="w-5 h-5" {...props} /> },
    { label: "Database Backup", icon: (props) => <DatabaseBackup className="w-5 h-5" {...props} /> },
    { label: "Diamond", icon: (props) => <Diamond className="w-5 h-5" {...props} /> },
    { label: "External Link", icon: (props) => <ExternalLink className="w-5 h-5" {...props} /> },
    { label: "File Check", icon: (props) => <FileCheck className="w-5 h-5" {...props} /> },
    { label: "Film", icon: (props) => <Film className="w-5 h-5" {...props} /> },
    { label: "Fingerprint", icon: (props) => <Fingerprint className="w-5 h-5" {...props} /> },
    { label: "Folder", icon: (props) => <Folder className="w-5 h-5" {...props} /> },
    { label: "Gavel", icon: (props) => <Gavel className="w-5 h-5" {...props} /> },
    { label: "Git Branch", icon: (props) => <GitBranch className="w-5 h-5" {...props} /> },
    { label: "Handshake", icon: (props) => <Handshake className="w-5 h-5" {...props} /> },
    { label: "Heart", icon: (props) => <Heart className="w-5 h-5" {...props} /> },
    { label: "Image", icon: (props) => <Image className="w-5 h-5" {...props} /> },
    { label: "Info", icon: (props) => <Info className="w-5 h-5" {...props} /> },
    { label: "Kanban", icon: (props) => <Kanban className="w-5 h-5" {...props} /> },
    { label: "Key", icon: (props) => <Key className="w-5 h-5" {...props} /> },
    { label: "Laptop", icon: (props) => <Laptop className="w-5 h-5" {...props} /> },
    { label: "Layout Dashboard", icon: (props) => <LayoutDashboard className="w-5 h-5" {...props} /> },
    { label: "Locate", icon: (props) => <Locate className="w-5 h-5" {...props} /> },
    { label: "Message Square", icon: (props) => <MessageSquare className="w-5 h-5" {...props} /> },
    { label: "Monitor", icon: (props) => <Monitor className="w-5 h-5" {...props} /> },
    { label: "Mouse Pointer", icon: (props) => <MousePointer className="w-5 h-5" {...props} /> },
    { label: "Network", icon: (props) => <Network className="w-5 h-5" {...props} /> },
    { label: "Package", icon: (props) => <Package className="w-5 h-5" {...props} /> },
    { label: "Palette", icon: (props) => <Palette className="w-5 h-5" {...props} /> },
    { label: "Pen Tool", icon: (props) => <PenTool className="w-5 h-5" {...props} /> },
    { label: "Pencil", icon: (props) => <Pencil className="w-5 h-5" {...props} /> },
    { label: "Power", icon: (props) => <Power className="w-5 h-5" {...props} /> },
    { label: "Printer", icon: (props) => <Printer className="w-5 h-5" {...props} /> },
    { label: "Puzzle", icon: (props) => <Puzzle className="w-5 h-5" {...props} /> },
    { label: "Refresh", icon: (props) => <RefreshCcw className="w-5 h-5" {...props} /> },
    { label: "Rotate", icon: (props) => <RotateCcw className="w-5 h-5" {...props} /> },
    { label: "RSS", icon: (props) => <Rss className="w-5 h-5" {...props} /> },
    { label: "Save", icon: (props) => <Save className="w-5 h-5" {...props} /> },
    { label: "Scaling", icon: (props) => <Scaling className="w-5 h-5" {...props} /> },
    { label: "Scan Text", icon: (props) => <ScanText className="w-5 h-5" {...props} /> },
    { label: "Signal", icon: (props) => <Signal className="w-5 h-5" {...props} /> },
    { label: "Skull", icon: (props) => <Skull className="w-5 h-5" {...props} /> },
    { label: "Sun", icon: (props) => <Sun className="w-5 h-5" {...props} /> },
    { label: "Tent", icon: (props) => <Tent className="w-5 h-5" {...props} /> },
    { label: "Ticket", icon: (props) => <Ticket className="w-5 h-5" {...props} /> },
    { label: "Timer", icon: (props) => <Timer className="w-5 h-5" {...props} /> },
    { label: "Trending Down", icon: (props) => <TrendingDown className="w-5 h-5" {...props} /> },
    { label: "Truck", icon: (props) => <Truck className="w-5 h-5" {...props} /> },
    { label: "User X", icon: (props) => <UserX className="w-5 h-5" {...props} /> },
    { label: "Vote", icon: (props) => <Vote className="w-5 h-5" {...props} /> },
    { label: "Wand", icon: (props) => <Wand className="w-5 h-5" {...props} /> },
    { label: "Warehouse", icon: (props) => <Warehouse className="w-5 h-5" {...props} /> },
    { label: "Watch", icon: (props) => <Watch className="w-5 h-5" {...props} /> },

];

export const SOCIAL_ICONS_REGISTRY: IconOption[] = [
    {
        label: "Facebook",
        icon: (props) => <IconBrandFacebook size={20} {...props} />,
    },

    {
        label: "Github",
        icon: (props) => <IconBrandGithub size={20} {...props} />,
    },
    {
        label: "Instagram",
        icon: (props) => <IconBrandInstagram size={20} {...props} />,
    },
    {
        label: "Linkedin",
        icon: (props) => <IconBrandLinkedin size={20} {...props} />,
    },
    {
        label: "X",
        icon: (props) => <IconBrandX size={20} {...props} />,
    },
    {
        label: "Youtube",
        icon: (props) => <IconBrandYoutube size={20} {...props} />,
    },
    {
        label: "Dribble",
        icon: (props) => <IconBrandDribbble size={20} {...props} />,
    },
    {
        label: "Website",
        icon: (props) => <Globe size={20} {...props} />,
    },
];
