import { GenericTemplateSchema } from "@/schemas/templates.schema";

export const F_STATIC_DATA: GenericTemplateSchema = {
    id: "cmcavetnq0000c7aqmtz9vb3v",
    name: "finance",
    thumbnailUrl: "/finance_template.png",
    theme: {
        "--template-font": "'Poppins', sans-serif",
        "--template-primary": "#f4f4f4",
        "--template-secondary": "#1F2F28",
        "--template-accent-primary": "#3b82f6",
        "--template-accent-secondary": "#60a5fa",
        "--template-btn": "#2563eb",
        "--template-text-primary": "#f8fafc",
        "--template-text-secondary": "#cbd5e1",
        "--template-text-accent-primary": "#93c5fd",
        "--template-text-accent-secondary": "#bae6fd",
        "--template-text-accent-tertiary": "#11111",
        "--template-text-btn": "#ffffff",
    },
    sections: [
        {
            type: "navbar",
            sectionName: "Navbar",
            data: {},
            isFixed: true,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "hero",
            sectionName: "Hero",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "featured-services",
            sectionName: "About",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "about",
            sectionName: "About",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "services",
            sectionName: "About",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "blogs",
            sectionName: "About",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "team",
            sectionName: "Team",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "why-choose-us",
            sectionName: "Team",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "projects",
            sectionName: "Projects",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },

        {
            type: "client",
            sectionName: "Client",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "gallery",
            sectionName: "Gallery",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "testimonials",
            sectionName: "Testimonials",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "service-catalog",
            sectionName: "Service Catalog",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },

        {
            type: "contact",
            sectionName: "Contact",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "contact widgets",
            sectionName: "Contact Widgets",
            data: {},
            isFixed: false,
            isEditable: true,
            isHidden: false,
        },
        {
            type: "footer",
            sectionName: "Footer",
            data: {},
            isFixed: true,
            isEditable: true,
            isHidden: false,
        },
    ],
};
