export * from "./about.section";
export * from "./blogs.section";
export * from "./contact.section";
export * from "./faq.section";
export * from "./featured-services.section";
export * from "./footer.section";
export * from "./gallery.section";
export * from "./hero.section";
export * from "./logos.section";
export * from "./navbar.section";
export * from "./newsletter.section";
export * from "./projects.section";
export * from "./service-catalog.section";
export * from "./services.section";
export * from "./stats.section";
export * from "./team.section";
export * from "./testimonials.section";
export * from "./timeline.section";

