name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/ReachooutApp

            # Pull latest changes
            git pull origin main

            # Deploy backend only
            cd server
            pnpm install
            pnpm build
            
            # Restart the server using the compiled JavaScript
            pm2 restart backend || pm2 start dist/server.js --name backend
          EOF
